"""add course id colun in students table

Revision ID: e07ed8ce349a
Revises: 3dde3ed79e5a
Create Date: 2024-04-04 09:42:12.072143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07ed8ce349a'
down_revision = '3dde3ed79e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk-students-courses', 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk-students-courses', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
